version: 2
updates:
  # Keep npm dependencies updated (root of the repo)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Keep GitHub Actions (workflows) updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
