name: BR Assistant (final)
on:
  push:
    branches: [branch-protection-test]   # run on your PR branch only
  workflow_dispatch:                     # optional manual button

permissions:
  statuses: write
  contents: read

jobs:
  publish-status:
    name: br-assistant
    runs-on: ubuntu-latest
    steps:
      - name: Publish success status on this commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,                  // <-- head commit of this push
            state: "success",
            context: "br-assistant",           // <-- the status name that will show in PR checks
            description: "BR Assistant (final) check via push",
            target_url: "https://github.com/" + context.repo.owner + "/" + context.repo.repo + "/actions/runs/" + context.runId
          })
