name: BR Assistant Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}  # minimal permissions

jobs:
  br-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "BR Assistant check passed ✅"
