name: BR Assistant
on:
  workflow_dispatch:   # manual button (ignore if missing)
  push:
    branches: [main]   # <-- this forces a run on any commit to main

permissions:
  contents: read
  pull-requests: write
  statuses: write
  issues: write

jobs:
  br-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity
        run: echo BR_Assistant_sanity_OK
