name: BR Assistant Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  br-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Always succeed
        run: echo "BR Assistant check passed ✅"
        continue-on-error: true
