name: BR Assistant (final)

on:
  pull_request:
    branches: [main]                 # runs whenever a PR targets main
    types: [opened, reopened, synchronize]

jobs:
  br-assistant:
    name: br-assistant               # <-- this labels the PR check as “BR Assistant (final) / br-assistant”
    runs-on: ubuntu-latest
    steps:
      - run: echo "BR Assistant check OK"
