name: BR Assistant
on:
  workflow_dispatch:          # manual button; should succeed with a no-op
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  br-assistant:
    name: br-assistant
    runs-on: ubuntu-latest
    steps:
      # --- Manual run path (no PR context) ---
      - name: Manual run sanity
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "✅ BR Assistant manual run OK (no PR context)."

      # --- PR path (has PR context) ---
      - name: Capture PR SHA
        if: ${{ github.event_name == 'pull_request' }}
        id: sha
        run: echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BR_ASSISTANT_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "🤖 BuiltRoot Assistant is active on this PR.\n\nRun: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}"
            });

      - name: Publish passing status
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        env:
          SHA: ${{ steps.sha.outputs.sha }}
        with:
          github-token: ${{ secrets.BR_ASSISTANT_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.SHA,
              state: "success",
              context: "br-assistant",
              description: "BuiltRoot Assistant status check passed",
              target_url: "https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}"
            });
