name: BR Assistant
on:
  workflow_dispatch:          # 👈 NEW: lets you run it manually from Actions tab
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write
  statuses: write
