name: BR Assistant
on:
  workflow_dispatch:
  push:
    branches: [main]   # temp to force a run on main

permissions:
  contents: read
  pull-requests: write
  statuses: write
  issues: write

jobs:
  br-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Show event
        run: echo "Event: ${{ github.event_name }} ✅"
