name: BR Assistant
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  statuses: write
  issues: write

jobs:
  br-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity
        run: echo BR_Assistant_sanity_OK
