name: BR Assistant (final)
on:
  pull_request:
    types: [opened, reopened, synchronize]  # runs on every PR update
  workflow_dispatch:                         # manual button if you ever need it

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  publish-status:
    name: br-assistant
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR SHA
        id: sha
        run: echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Publish success status on PR head
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
        env:
          SHA: ${{ steps.sha.outputs.sha }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: process.env.SHA,
            state: "success",
            context: "br-assistant",
            description: "BuiltRoot Assistant (final) check passed",
            target_url: "https://github.com/" + context.repo.owner + "/" + context.repo.repo + "/actions/runs/" + context.runId
          });
