name: BR Required Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  br-check:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "BR Required check passed ✅"
