name: BR Required Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  br-check:
    runs-on: ubuntu-latest
    steps:
      - name: Always succeed
        run: echo "BR Required check passed ✅"
        continue-on-error: true
