name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Only run Node steps if a package.json exists
      - name: Install deps (safe)
        if: hashFiles('package.json') != ''
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --prefer-offline --no-audit --no-fund
          fi

      - name: Lint
        if: hashFiles('package.json') != ''
        run: npm run lint --if-present

      - name: Test
        if: hashFiles('package.json') != ''
        run: npm test --if-present -- --ci

      - name: Build
        if: hashFiles('package.json') != ''
        run: npm run build --if-present
