name: Uptime Ping (/api/status)

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # still lets you run manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/status
        run: |
          curl -sS https://built-root-main.vercel.app/api/status || exit 1
