name: Uptime Ping (/api/status)

on:
  # Runs every 10 minutes; you can change this later.
  schedule:
    - cron: "*/10 * * * *"
  # Lets you run it on-demand from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Ping status endpoint
        env:
          PING_URL: https://built-root-main.vercel.app/api/status
        run: |
          echo "Pinging $PING_URL"
          # Call the endpoint; capture body + HTTP code
          HTTP_CODE=$(curl -sS -m 15 -w "%{http_code}" -o /tmp/resp "$PING_URL" || true)
          echo "HTTP_CODE=$HTTP_CODE"
          echo "Response (first 200 chars):"
          head -c 200 /tmp/resp || true
          # Fail the job if not 200
          test "$HTTP_CODE" = "200"
